syntax = "proto3";

package ThreatBook_CloudAPI_V3;

import "google/protobuf/struct.proto";

option go_package = "miner/grpc-service/ThreatBook_CloudAPI_V3";

service ThreatBook_CloudAPI_V3 {
  rpc IpReputation(IpReputationRequest) returns (IpReputationResponse) {}
  rpc DomainQuery(DomainQueryRequest) returns (DomainQueryResponse) {}
  rpc SceneDns(SceneDnsRequest) returns (SceneDnsResponse) {}
}

message IpReputationRequest {
  string resource = 1;
  string lang = 2;
}

message IpReputationResponse {
  int32 http_status = 1;
  string raw_body = 2;
  google.protobuf.Value raw_json = 3;
}

message DomainQueryRequest {
  string resource = 1;
  string lang = 2;
  string exclude = 3;
}

message DomainQueryResponse {
  int32 http_status = 1;
  string raw_body = 2;
  google.protobuf.Value raw_json = 3;
}

message SceneDnsRequest {
  string resource = 1;
  string lang = 2;
}

message SceneDnsResponse {
  int32 http_status = 1;
  string raw_body = 2;
  google.protobuf.Value raw_json = 3;
}
